apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../crds/purelb.io_servicegroups.yaml
- ../crds/purelb.io_lbnodeagents.yaml
- ../components/gobgp/gobgp-bgpconfig-crd.yaml
- ../components/gobgp/gobgp-bgpnodestatus-crd.yaml
