apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: purelb
  name: purelb:k8gobgp
rules:
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ''
  resources:
  - nodes
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - patch
- apiGroups:
  - bgp.purelb.io
  resources:
  - bgpnodestatuses
  - configs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bgp.purelb.io
  resources:
  - bgpnodestatuses/status
  - configs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - bgp.purelb.io
  resources:
  - configs/finalizers
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: purelb
  name: purelb:k8gobgp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: purelb:k8gobgp
subjects:
- kind: ServiceAccount
  name: lbnodeagent
  namespace: purelb-system
