// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package addrguard

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type addrguardGuardConfig struct {
	_    structs.HostLayout
	Mode uint32
}

type addrguardIn6Addr struct {
	_    structs.HostLayout
	In6U struct {
		_       structs.HostLayout
		U6Addr8 [16]uint8
	}
}

type addrguardPortKey struct {
	_      structs.HostLayout
	Addr   [4]uint32
	Port   uint16
	Proto  uint8
	Family uint8
}

type addrguardVipCounters struct {
	_         structs.HostLayout
	Drop      uint64
	WouldDrop uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	addrguardMapAgConfig  = "ag_config"
	addrguardMapAgPorts   = "ag_ports"
	addrguardMapAgProtos  = "ag_protos"
	addrguardMapAgReasons = "ag_reasons"
	addrguardMapAgVip4    = "ag_vip4"
	addrguardMapAgVip6    = "ag_vip6"
	addrguardProgAgTcx    = "ag_tcx"
	addrguardProgAgXdp    = "ag_xdp"
)

// loadAddrguard returns the embedded CollectionSpec for addrguard.
func loadAddrguard() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_AddrguardBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load addrguard: %w", err)
	}

	return spec, err
}

// loadAddrguardObjects loads addrguard and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*addrguardObjects
//	*addrguardPrograms
//	*addrguardMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadAddrguardObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadAddrguard()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// addrguardSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type addrguardSpecs struct {
	addrguardProgramSpecs
	addrguardMapSpecs
	addrguardVariableSpecs
}

// addrguardProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type addrguardProgramSpecs struct {
	AgTcx *ebpf.ProgramSpec `ebpf:"ag_tcx"`
	AgXdp *ebpf.ProgramSpec `ebpf:"ag_xdp"`
}

// addrguardMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type addrguardMapSpecs struct {
	AgConfig  *ebpf.MapSpec `ebpf:"ag_config"`
	AgPorts   *ebpf.MapSpec `ebpf:"ag_ports"`
	AgProtos  *ebpf.MapSpec `ebpf:"ag_protos"`
	AgReasons *ebpf.MapSpec `ebpf:"ag_reasons"`
	AgVip4    *ebpf.MapSpec `ebpf:"ag_vip4"`
	AgVip6    *ebpf.MapSpec `ebpf:"ag_vip6"`
}

// addrguardVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type addrguardVariableSpecs struct {
}

// addrguardObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadAddrguardObjects or ebpf.CollectionSpec.LoadAndAssign.
type addrguardObjects struct {
	addrguardPrograms
	addrguardMaps
	addrguardVariables
}

func (o *addrguardObjects) Close() error {
	return _AddrguardClose(
		&o.addrguardPrograms,
		&o.addrguardMaps,
	)
}

// addrguardMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadAddrguardObjects or ebpf.CollectionSpec.LoadAndAssign.
type addrguardMaps struct {
	AgConfig  *ebpf.Map `ebpf:"ag_config"`
	AgPorts   *ebpf.Map `ebpf:"ag_ports"`
	AgProtos  *ebpf.Map `ebpf:"ag_protos"`
	AgReasons *ebpf.Map `ebpf:"ag_reasons"`
	AgVip4    *ebpf.Map `ebpf:"ag_vip4"`
	AgVip6    *ebpf.Map `ebpf:"ag_vip6"`
}

func (m *addrguardMaps) Close() error {
	return _AddrguardClose(
		m.AgConfig,
		m.AgPorts,
		m.AgProtos,
		m.AgReasons,
		m.AgVip4,
		m.AgVip6,
	)
}

// addrguardVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadAddrguardObjects or ebpf.CollectionSpec.LoadAndAssign.
type addrguardVariables struct {
}

// addrguardPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadAddrguardObjects or ebpf.CollectionSpec.LoadAndAssign.
type addrguardPrograms struct {
	AgTcx *ebpf.Program `ebpf:"ag_tcx"`
	AgXdp *ebpf.Program `ebpf:"ag_xdp"`
}

func (p *addrguardPrograms) Close() error {
	return _AddrguardClose(
		p.AgTcx,
		p.AgXdp,
	)
}

func _AddrguardClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed addrguard_bpfel.o
var _AddrguardBytes []byte
