baseURL = "https://purelb.github.io/purelb/"
languageCode = "en-us"
title = "PureLB"
theme = "hugo-book"

enableGitInfo = true
googleAnalytics = "G-K7X5FYG9N9"

[params]
  BookTheme = "auto"
  BookToC = true
  BookSearch = true
  BookSection = "docs"
  BookLogo = "images/purelb.png"
  BookFavicon = "images/favicon.png"
  BookRepo = "https://github.com/purelb/purelb"
  BookEditPath = "edit/main/website/content/"

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  codeFences = true
  guessSyntax = true
  style = "monokai"
  tabWidth = 2

[outputs]
  home = ["HTML", "RSS"]
