---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: purelb
  name: allocator
  namespace: purelb-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: purelb
  name: lbnodeagent
  namespace: purelb-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: purelb
  name: purelb:allocator
rules:
- apiGroups:
  - purelb.io
  resources:
  - servicegroups
  - lbnodeagents
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ''
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ''
  resources:
  - services/status
  verbs:
  - update
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: purelb
  name: purelb:lbnodeagent
rules:
- apiGroups:
  - purelb.io
  resources:
  - servicegroups
  - lbnodeagents
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ''
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - get
  - list
# Leases are used for leader election (subnet-aware election via K8s leases)
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: purelb
  name: pod-lister
  namespace: purelb-system
rules:
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: purelb
  name: purelb:allocator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: purelb:allocator
subjects:
- kind: ServiceAccount
  name: allocator
  namespace: purelb-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: purelb
  name: purelb:lbnodeagent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: purelb:lbnodeagent
subjects:
- kind: ServiceAccount
  name: lbnodeagent
  namespace: purelb-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: purelb
  name: pod-lister
  namespace: purelb-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-lister
subjects:
- kind: ServiceAccount
  name: lbnodeagent
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: purelb
    component: lbnodeagent
  name: lbnodeagent
  namespace: purelb-system
spec:
  selector:
    matchLabels:
      app: purelb
      component: lbnodeagent
  template:
    metadata:
      annotations:
        prometheus.io/port: '7472'
        prometheus.io/scrape: 'true'
        # Required to allow signal delivery for graceful termination
        container.apparmor.security.beta.kubernetes.io/lbnodeagent: unconfined
      labels:
        app: purelb
        component: lbnodeagent
    spec:
      containers:
      - env:
        - name: DEFAULT_ANNOUNCER
          value: "PureLB"
        - name: PURELB_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: PURELB_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: PURELB_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PURELB_POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        # Lease-based election configuration
        - name: PURELB_LEASE_DURATION
          value: "10s"
        - name: PURELB_RENEW_DEADLINE
          value: "7s"
        - name: PURELB_RETRY_PERIOD
          value: "2s"
        image: ghcr.io/purelb/purelb/lbnodeagent:VERSION_TAG
        imagePullPolicy: IfNotPresent
        name: lbnodeagent
        ports:
        - containerPort: 7472
          name: monitoring
        resources:
          limits:
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            drop:
            - ALL
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: lbnodeagent
      # Allow enough time for graceful shutdown:
      # - Mark unhealthy + ForceSync (~1s)
      # - Traffic drain wait (2s)
      # - Lease deletion + cleanup (~1s)
      # Plus buffer for slow API server responses
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: purelb
    component: allocator
  name: allocator
  namespace: purelb-system
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: purelb
      component: allocator
  template:
    metadata:
      annotations:
        prometheus.io/port: '7472'
        prometheus.io/scrape: 'true'
      labels:
        app: purelb
        component: allocator
    spec:
      containers:
      - image: ghcr.io/purelb/purelb/allocator:VERSION_TAG
        imagePullPolicy: IfNotPresent
        env:
        - name: NETBOX_USER_TOKEN
          valueFrom:
            secretKeyRef:
              name: netbox-client
              key: user-token
              optional: true
        - name: DEFAULT_ANNOUNCER
          value: "PureLB"
        name: allocator
        ports:
        - containerPort: 7472
          name: monitoring
        resources:
          limits:
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: allocator
      terminationGracePeriodSeconds: 0
