// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/ipam/v1/ipam.proto

package ipamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllocateRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Pool       string                 `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`                               // ServiceGroup name
	Service    string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`                         // namespace/name (sidecar uses for idempotency)
	SharingKey string                 `protobuf:"bytes,3,opt,name=sharing_key,json=sharingKey,proto3" json:"sharing_key,omitempty"` // purelb.io/allow-shared-ip value (may be empty)
	// Types that are valid to be assigned to Selector:
	//
	//	*AllocateRequest_Explicit
	//	*AllocateRequest_Families
	Selector      isAllocateRequest_Selector `protobuf_oneof:"selector"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateRequest) Reset() {
	*x = AllocateRequest{}
	mi := &file_api_ipam_v1_ipam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateRequest) ProtoMessage() {}

func (x *AllocateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ipam_v1_ipam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateRequest.ProtoReflect.Descriptor instead.
func (*AllocateRequest) Descriptor() ([]byte, []int) {
	return file_api_ipam_v1_ipam_proto_rawDescGZIP(), []int{0}
}

func (x *AllocateRequest) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *AllocateRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *AllocateRequest) GetSharingKey() string {
	if x != nil {
		return x.SharingKey
	}
	return ""
}

func (x *AllocateRequest) GetSelector() isAllocateRequest_Selector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *AllocateRequest) GetExplicit() *ExplicitIPs {
	if x != nil {
		if x, ok := x.Selector.(*AllocateRequest_Explicit); ok {
			return x.Explicit
		}
	}
	return nil
}

func (x *AllocateRequest) GetFamilies() *FamilyRequest {
	if x != nil {
		if x, ok := x.Selector.(*AllocateRequest_Families); ok {
			return x.Families
		}
	}
	return nil
}

type isAllocateRequest_Selector interface {
	isAllocateRequest_Selector()
}

type AllocateRequest_Explicit struct {
	Explicit *ExplicitIPs `protobuf:"bytes,4,opt,name=explicit,proto3,oneof"` // user-requested specific IPs
}

type AllocateRequest_Families struct {
	Families *FamilyRequest `protobuf:"bytes,5,opt,name=families,proto3,oneof"` // auto-pick by family
}

func (*AllocateRequest_Explicit) isAllocateRequest_Selector() {}

func (*AllocateRequest_Families) isAllocateRequest_Selector() {}

type ExplicitIPs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ips           []string               `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplicitIPs) Reset() {
	*x = ExplicitIPs{}
	mi := &file_api_ipam_v1_ipam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplicitIPs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplicitIPs) ProtoMessage() {}

func (x *ExplicitIPs) ProtoReflect() protoreflect.Message {
	mi := &file_api_ipam_v1_ipam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplicitIPs.ProtoReflect.Descriptor instead.
func (*ExplicitIPs) Descriptor() ([]byte, []int) {
	return file_api_ipam_v1_ipam_proto_rawDescGZIP(), []int{1}
}

func (x *ExplicitIPs) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

type FamilyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WantIpv4      bool                   `protobuf:"varint,1,opt,name=want_ipv4,json=wantIpv4,proto3" json:"want_ipv4,omitempty"`
	WantIpv6      bool                   `protobuf:"varint,2,opt,name=want_ipv6,json=wantIpv6,proto3" json:"want_ipv6,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FamilyRequest) Reset() {
	*x = FamilyRequest{}
	mi := &file_api_ipam_v1_ipam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FamilyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyRequest) ProtoMessage() {}

func (x *FamilyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ipam_v1_ipam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyRequest.ProtoReflect.Descriptor instead.
func (*FamilyRequest) Descriptor() ([]byte, []int) {
	return file_api_ipam_v1_ipam_proto_rawDescGZIP(), []int{2}
}

func (x *FamilyRequest) GetWantIpv4() bool {
	if x != nil {
		return x.WantIpv4
	}
	return false
}

func (x *FamilyRequest) GetWantIpv6() bool {
	if x != nil {
		return x.WantIpv6
	}
	return false
}

type AllocateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ips           []*AllocatedIP         `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateResponse) Reset() {
	*x = AllocateResponse{}
	mi := &file_api_ipam_v1_ipam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateResponse) ProtoMessage() {}

func (x *AllocateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ipam_v1_ipam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateResponse.ProtoReflect.Descriptor instead.
func (*AllocateResponse) Descriptor() ([]byte, []int) {
	return file_api_ipam_v1_ipam_proto_rawDescGZIP(), []int{3}
}

func (x *AllocateResponse) GetIps() []*AllocatedIP {
	if x != nil {
		return x.Ips
	}
	return nil
}

type AllocatedIP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"` // Reserved for future per-IP metadata (e.g. lease TTL).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocatedIP) Reset() {
	*x = AllocatedIP{}
	mi := &file_api_ipam_v1_ipam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocatedIP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocatedIP) ProtoMessage() {}

func (x *AllocatedIP) ProtoReflect() protoreflect.Message {
	mi := &file_api_ipam_v1_ipam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocatedIP.ProtoReflect.Descriptor instead.
func (*AllocatedIP) Descriptor() ([]byte, []int) {
	return file_api_ipam_v1_ipam_proto_rawDescGZIP(), []int{4}
}

func (x *AllocatedIP) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// ReleaseRequest uses oneof to prevent the "empty string releases all"
// footgun.
type ReleaseRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Pool    string                 `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	Service string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	// Types that are valid to be assigned to Target:
	//
	//	*ReleaseRequest_Ip
	//	*ReleaseRequest_All
	Target        isReleaseRequest_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_api_ipam_v1_ipam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ipam_v1_ipam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_api_ipam_v1_ipam_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseRequest) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *ReleaseRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ReleaseRequest) GetTarget() isReleaseRequest_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ReleaseRequest) GetIp() string {
	if x != nil {
		if x, ok := x.Target.(*ReleaseRequest_Ip); ok {
			return x.Ip
		}
	}
	return ""
}

func (x *ReleaseRequest) GetAll() bool {
	if x != nil {
		if x, ok := x.Target.(*ReleaseRequest_All); ok {
			return x.All
		}
	}
	return false
}

type isReleaseRequest_Target interface {
	isReleaseRequest_Target()
}

type ReleaseRequest_Ip struct {
	Ip string `protobuf:"bytes,3,opt,name=ip,proto3,oneof"` // release a specific IP
}

type ReleaseRequest_All struct {
	All bool `protobuf:"varint,4,opt,name=all,proto3,oneof"` // release all of the service's IPs
}

func (*ReleaseRequest_Ip) isReleaseRequest_Target() {}

func (*ReleaseRequest_All) isReleaseRequest_Target() {}

type ReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseResponse) Reset() {
	*x = ReleaseResponse{}
	mi := &file_api_ipam_v1_ipam_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResponse) ProtoMessage() {}

func (x *ReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ipam_v1_ipam_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseResponse) Descriptor() ([]byte, []int) {
	return file_api_ipam_v1_ipam_proto_rawDescGZIP(), []int{6}
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pool          string                 `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_api_ipam_v1_ipam_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ipam_v1_ipam_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_api_ipam_v1_ipam_proto_rawDescGZIP(), []int{7}
}

func (x *StatsRequest) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

type StatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InUseV4          uint64                 `protobuf:"varint,1,opt,name=in_use_v4,json=inUseV4,proto3" json:"in_use_v4,omitempty"`
	InUseV6          uint64                 `protobuf:"varint,2,opt,name=in_use_v6,json=inUseV6,proto3" json:"in_use_v6,omitempty"`
	SizeV4           uint64                 `protobuf:"varint,3,opt,name=size_v4,json=sizeV4,proto3" json:"size_v4,omitempty"`
	SizeV6           uint64                 `protobuf:"varint,4,opt,name=size_v6,json=sizeV6,proto3" json:"size_v6,omitempty"`
	HasKnownCapacity bool                   `protobuf:"varint,5,opt,name=has_known_capacity,json=hasKnownCapacity,proto3" json:"has_known_capacity,omitempty"`
	DisplayAddresses []string               `protobuf:"bytes,6,rep,name=display_addresses,json=displayAddresses,proto3" json:"display_addresses,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_api_ipam_v1_ipam_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ipam_v1_ipam_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_api_ipam_v1_ipam_proto_rawDescGZIP(), []int{8}
}

func (x *StatsResponse) GetInUseV4() uint64 {
	if x != nil {
		return x.InUseV4
	}
	return 0
}

func (x *StatsResponse) GetInUseV6() uint64 {
	if x != nil {
		return x.InUseV6
	}
	return 0
}

func (x *StatsResponse) GetSizeV4() uint64 {
	if x != nil {
		return x.SizeV4
	}
	return 0
}

func (x *StatsResponse) GetSizeV6() uint64 {
	if x != nil {
		return x.SizeV6
	}
	return 0
}

func (x *StatsResponse) GetHasKnownCapacity() bool {
	if x != nil {
		return x.HasKnownCapacity
	}
	return false
}

func (x *StatsResponse) GetDisplayAddresses() []string {
	if x != nil {
		return x.DisplayAddresses
	}
	return nil
}

var File_api_ipam_v1_ipam_proto protoreflect.FileDescriptor

const file_api_ipam_v1_ipam_proto_rawDesc = "" +
	"\n" +
	"\x16api/ipam/v1/ipam.proto\x12\x0epurelb.ipam.v1\"\xe4\x01\n" +
	"\x0fAllocateRequest\x12\x12\n" +
	"\x04pool\x18\x01 \x01(\tR\x04pool\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1f\n" +
	"\vsharing_key\x18\x03 \x01(\tR\n" +
	"sharingKey\x129\n" +
	"\bexplicit\x18\x04 \x01(\v2\x1b.purelb.ipam.v1.ExplicitIPsH\x00R\bexplicit\x12;\n" +
	"\bfamilies\x18\x05 \x01(\v2\x1d.purelb.ipam.v1.FamilyRequestH\x00R\bfamiliesB\n" +
	"\n" +
	"\bselector\"\x1f\n" +
	"\vExplicitIPs\x12\x10\n" +
	"\x03ips\x18\x01 \x03(\tR\x03ips\"I\n" +
	"\rFamilyRequest\x12\x1b\n" +
	"\twant_ipv4\x18\x01 \x01(\bR\bwantIpv4\x12\x1b\n" +
	"\twant_ipv6\x18\x02 \x01(\bR\bwantIpv6\"A\n" +
	"\x10AllocateResponse\x12-\n" +
	"\x03ips\x18\x01 \x03(\v2\x1b.purelb.ipam.v1.AllocatedIPR\x03ips\"\x1d\n" +
	"\vAllocatedIP\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"n\n" +
	"\x0eReleaseRequest\x12\x12\n" +
	"\x04pool\x18\x01 \x01(\tR\x04pool\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x10\n" +
	"\x02ip\x18\x03 \x01(\tH\x00R\x02ip\x12\x12\n" +
	"\x03all\x18\x04 \x01(\bH\x00R\x03allB\b\n" +
	"\x06target\"\x11\n" +
	"\x0fReleaseResponse\"\"\n" +
	"\fStatsRequest\x12\x12\n" +
	"\x04pool\x18\x01 \x01(\tR\x04pool\"\xd4\x01\n" +
	"\rStatsResponse\x12\x1a\n" +
	"\tin_use_v4\x18\x01 \x01(\x04R\ainUseV4\x12\x1a\n" +
	"\tin_use_v6\x18\x02 \x01(\x04R\ainUseV6\x12\x17\n" +
	"\asize_v4\x18\x03 \x01(\x04R\x06sizeV4\x12\x17\n" +
	"\asize_v6\x18\x04 \x01(\x04R\x06sizeV6\x12,\n" +
	"\x12has_known_capacity\x18\x05 \x01(\bR\x10hasKnownCapacity\x12+\n" +
	"\x11display_addresses\x18\x06 \x03(\tR\x10displayAddresses2\xe7\x01\n" +
	"\x04IPAM\x12M\n" +
	"\bAllocate\x12\x1f.purelb.ipam.v1.AllocateRequest\x1a .purelb.ipam.v1.AllocateResponse\x12J\n" +
	"\aRelease\x12\x1e.purelb.ipam.v1.ReleaseRequest\x1a\x1f.purelb.ipam.v1.ReleaseResponse\x12D\n" +
	"\x05Stats\x12\x1c.purelb.ipam.v1.StatsRequest\x1a\x1d.purelb.ipam.v1.StatsResponseB\x1eZ\x1cpurelb.io/api/ipam/v1;ipamv1b\x06proto3"

var (
	file_api_ipam_v1_ipam_proto_rawDescOnce sync.Once
	file_api_ipam_v1_ipam_proto_rawDescData []byte
)

func file_api_ipam_v1_ipam_proto_rawDescGZIP() []byte {
	file_api_ipam_v1_ipam_proto_rawDescOnce.Do(func() {
		file_api_ipam_v1_ipam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ipam_v1_ipam_proto_rawDesc), len(file_api_ipam_v1_ipam_proto_rawDesc)))
	})
	return file_api_ipam_v1_ipam_proto_rawDescData
}

var file_api_ipam_v1_ipam_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_ipam_v1_ipam_proto_goTypes = []any{
	(*AllocateRequest)(nil),  // 0: purelb.ipam.v1.AllocateRequest
	(*ExplicitIPs)(nil),      // 1: purelb.ipam.v1.ExplicitIPs
	(*FamilyRequest)(nil),    // 2: purelb.ipam.v1.FamilyRequest
	(*AllocateResponse)(nil), // 3: purelb.ipam.v1.AllocateResponse
	(*AllocatedIP)(nil),      // 4: purelb.ipam.v1.AllocatedIP
	(*ReleaseRequest)(nil),   // 5: purelb.ipam.v1.ReleaseRequest
	(*ReleaseResponse)(nil),  // 6: purelb.ipam.v1.ReleaseResponse
	(*StatsRequest)(nil),     // 7: purelb.ipam.v1.StatsRequest
	(*StatsResponse)(nil),    // 8: purelb.ipam.v1.StatsResponse
}
var file_api_ipam_v1_ipam_proto_depIdxs = []int32{
	1, // 0: purelb.ipam.v1.AllocateRequest.explicit:type_name -> purelb.ipam.v1.ExplicitIPs
	2, // 1: purelb.ipam.v1.AllocateRequest.families:type_name -> purelb.ipam.v1.FamilyRequest
	4, // 2: purelb.ipam.v1.AllocateResponse.ips:type_name -> purelb.ipam.v1.AllocatedIP
	0, // 3: purelb.ipam.v1.IPAM.Allocate:input_type -> purelb.ipam.v1.AllocateRequest
	5, // 4: purelb.ipam.v1.IPAM.Release:input_type -> purelb.ipam.v1.ReleaseRequest
	7, // 5: purelb.ipam.v1.IPAM.Stats:input_type -> purelb.ipam.v1.StatsRequest
	3, // 6: purelb.ipam.v1.IPAM.Allocate:output_type -> purelb.ipam.v1.AllocateResponse
	6, // 7: purelb.ipam.v1.IPAM.Release:output_type -> purelb.ipam.v1.ReleaseResponse
	8, // 8: purelb.ipam.v1.IPAM.Stats:output_type -> purelb.ipam.v1.StatsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_ipam_v1_ipam_proto_init() }
func file_api_ipam_v1_ipam_proto_init() {
	if File_api_ipam_v1_ipam_proto != nil {
		return
	}
	file_api_ipam_v1_ipam_proto_msgTypes[0].OneofWrappers = []any{
		(*AllocateRequest_Explicit)(nil),
		(*AllocateRequest_Families)(nil),
	}
	file_api_ipam_v1_ipam_proto_msgTypes[5].OneofWrappers = []any{
		(*ReleaseRequest_Ip)(nil),
		(*ReleaseRequest_All)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ipam_v1_ipam_proto_rawDesc), len(file_api_ipam_v1_ipam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ipam_v1_ipam_proto_goTypes,
		DependencyIndexes: file_api_ipam_v1_ipam_proto_depIdxs,
		MessageInfos:      file_api_ipam_v1_ipam_proto_msgTypes,
	}.Build()
	File_api_ipam_v1_ipam_proto = out.File
	file_api_ipam_v1_ipam_proto_goTypes = nil
	file_api_ipam_v1_ipam_proto_depIdxs = nil
}
